# -*- coding: utf-8 -*-
"""Calculadora do primeiro exercício.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10rG7yKzw_BfADq0Fvqknly3KRtNTX3Ae
"""

#calculadora python - tarefa do DSA

print('''Selecione a operação desejada:
1 - Adição
2 - Subtração
3 - Multplicação
4 - Divisão''')
#prompt na tela para seleção da operação matemática

mathoperator = input()
#receber a escolha do usuário

print("Digite o primeiro número:")
firstNumber = input()
#Usuário informa o primeiro número da operação

print("Digite o segundo número:")
secondNumber = input()
#Usuário informa o segundo número da operação

if mathoperator == "1": #adição
  result = int(firstNumber) + int(secondNumber)
  print("o resultado é: {}".format(result))
  #imprimir texto com o resultado da operação
elif mathoperator == "2": #subtração
  result = int(firstNumber) - int(secondNumber)
  print("o resultado é: {}".format(result))
elif mathoperator == "3": #multiplicação
  result = int(firstNumber) * int(secondNumber)
  print("o resultado é: {}".format(result))
elif mathoperator == "4": #divisão
  result = int(firstNumber) / int(secondNumber)
  print("o resultado é: {}".format(result))
else: #opção inválida selecionada
  print('Opção inválida')